baseURL = 'http://localhost:1313/'
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Rowe IT"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "Rowe IT" # Set a different text for the header on the home page
  subtitle = "Build a beautiful and simple website in minutes"
  mainSections = ["post","news"]
  logo = "img/cropped-pride-1.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Some Person"
  website = "yourwebsite.com"
  twitter = "roweit"
  linkedin = "rowe-it-limited"
  instagram = "rowe_it"

[[menu.main]]
    name = "Latest News"
    url = "news/"
    weight = 4

[[menu.main]]
    name = "Who We Are"
    url = "page/about/"
    weight = 1

[[menu.main]]
    identifier = "whatwedo"
    name = "What We Do"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
